### ISSUE TITLE
What does dev_rev.json mean?

### ISSUE THREAD

**Issue by jzhang38** [wzhouad/RE_improved_baseline#1]
Hi, thanks for your solid work!

May I ask how does dev_rev.json come from? It is not included in the TACRED dataset I download from LDC.

**Comment by wzhouad** [comment]
``dev_rev.json`` is the denoised development set proposed in the paper https://aclanthology.org/2020.acl-main.142.pdf. It can be obtained following the instructions in https://github.com/DFKI-NLP/tacrev.
