### ISSUE TITLE
Save and Load model 

### ISSUE THREAD

**Issue by fillipefbr** [wzhouad/RE_improved_baseline#2]
Hi, thank you so much for this repository and congratulations for your work!

Could you please update the code so that we can save and load the trained models? I trained a model based on your typed entity marker method and now I would like to load it and apply it to predict relations on new texts. I would appreciate if you can explain to me how to do it or give some examples.

Thank you!

**Comment by wzhouad** [comment]
You can refer to the [Pytorch docs](https://pytorch.org/tutorials/beginner/saving_loading_models.html) on how to save and load the model.
